# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\"(\n\x0cSimpleRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"m\n\rComplexRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\x12\x10\n\x08isActive\x18\x05 \x01(\x08\x12\x0c\n\x04tags\x18\x06 \x03(\t\"9\n\x0bLargeRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x81\x01\n\nDataPacket\x12%\n\x0esimple_records\x18\x01 \x03(\x0b\x32\r.SimpleRecord\x12\'\n\x0f\x63omplex_records\x18\x02 \x03(\x0b\x32\x0e.ComplexRecord\x12#\n\rlarge_records\x18\x03 \x03(\x0b\x32\x0c.LargeRecordb\x06proto3')
)




_SIMPLERECORD = _descriptor.Descriptor(
  name='SimpleRecord',
  full_name='SimpleRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SimpleRecord.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='SimpleRecord.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=54,
)


_COMPLEXRECORD = _descriptor.Descriptor(
  name='ComplexRecord',
  full_name='ComplexRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ComplexRecord.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ComplexRecord.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='ComplexRecord.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ComplexRecord.value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isActive', full_name='ComplexRecord.isActive', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='ComplexRecord.tags', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=165,
)


_LARGERECORD = _descriptor.Descriptor(
  name='LargeRecord',
  full_name='LargeRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LargeRecord.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='LargeRecord.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='LargeRecord.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=224,
)


_DATAPACKET = _descriptor.Descriptor(
  name='DataPacket',
  full_name='DataPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simple_records', full_name='DataPacket.simple_records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='complex_records', full_name='DataPacket.complex_records', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='large_records', full_name='DataPacket.large_records', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=356,
)

_DATAPACKET.fields_by_name['simple_records'].message_type = _SIMPLERECORD
_DATAPACKET.fields_by_name['complex_records'].message_type = _COMPLEXRECORD
_DATAPACKET.fields_by_name['large_records'].message_type = _LARGERECORD
DESCRIPTOR.message_types_by_name['SimpleRecord'] = _SIMPLERECORD
DESCRIPTOR.message_types_by_name['ComplexRecord'] = _COMPLEXRECORD
DESCRIPTOR.message_types_by_name['LargeRecord'] = _LARGERECORD
DESCRIPTOR.message_types_by_name['DataPacket'] = _DATAPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleRecord = _reflection.GeneratedProtocolMessageType('SimpleRecord', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLERECORD,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:SimpleRecord)
  ))
_sym_db.RegisterMessage(SimpleRecord)

ComplexRecord = _reflection.GeneratedProtocolMessageType('ComplexRecord', (_message.Message,), dict(
  DESCRIPTOR = _COMPLEXRECORD,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:ComplexRecord)
  ))
_sym_db.RegisterMessage(ComplexRecord)

LargeRecord = _reflection.GeneratedProtocolMessageType('LargeRecord', (_message.Message,), dict(
  DESCRIPTOR = _LARGERECORD,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:LargeRecord)
  ))
_sym_db.RegisterMessage(LargeRecord)

DataPacket = _reflection.GeneratedProtocolMessageType('DataPacket', (_message.Message,), dict(
  DESCRIPTOR = _DATAPACKET,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:DataPacket)
  ))
_sym_db.RegisterMessage(DataPacket)


# @@protoc_insertion_point(module_scope)
